import type { Metadata } from "next";
import { IBM_Plex_Sans, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/additional/navbar/Navbar";
import Image from "next/image";

const ibm = IBM_Plex_Sans({
  weight: ["700", "400", "300"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ready2.Study",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      className={cn("bg-primary text-secondary flex flex-col", ibm.className)}
      lang="en"
    >
      <body>
        <Navbar />
        <div className="mx-auto">{children}</div>
      </body>
    </html>
  );
}
